// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TwitterUala.Infrastructure;

#nullable disable

namespace TwitterUala.Migrations
{
    [DbContext(typeof(TwitterDbContext))]
    [Migration("20250303005443_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TwitterUala.Domain.Entities.Following", b =>
                {
                    b.Property<long>("IdFollowing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_following");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdFollowing"));

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("UsersToFollowId")
                        .HasColumnType("bigint")
                        .HasColumnName("users_to_follow_id");

                    b.HasKey("IdFollowing");

                    b.ToTable("following", (string)null);
                });

            modelBuilder.Entity("TwitterUala.Domain.Entities.Tweet", b =>
                {
                    b.Property<long>("IdTweet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_tweet");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdTweet"));

                    b.Property<long?>("FollowingIdFollowing")
                        .HasColumnType("bigint");

                    b.Property<string>("TweetMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tweet_message");

                    b.Property<DateTime>("TweetPosted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tweet_posted");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("IdTweet");

                    b.HasIndex("FollowingIdFollowing");

                    b.ToTable("tweet", (string)null);
                });

            modelBuilder.Entity("TwitterUala.Domain.Entities.Tweet", b =>
                {
                    b.HasOne("TwitterUala.Domain.Entities.Following", null)
                        .WithMany("TweetsUser")
                        .HasForeignKey("FollowingIdFollowing");
                });

            modelBuilder.Entity("TwitterUala.Domain.Entities.Following", b =>
                {
                    b.Navigation("TweetsUser");
                });
#pragma warning restore 612, 618
        }
    }
}
